export const adminRoutePaths = [
  '/admin/login',
  '/admin/',
  '/admin/activity',
  '/admin/tasks',
  '/admin/users',
  '/admin/roles',
  '/admin/departments',
  '/admin/audit',
  '/admin/settings',
  '/admin/introspection',
  '/admin/generator',
  '/admin/modules',
  '/admin/openapi-browser',
  '/admin/permissions',
] as const
